# Configure code highlighting
highlight:
  style: github-dark # https://xyproto.github.io/splash/docs/
# Configure Markdown rendering
goldmark:
  renderer:
    unsafe: true # Allow HTML in Markdown
  parser:
    attribute:
      block: true # Enable Markdown attributes
    wrapStandAloneImageWithinParagraph: false # Do not wrap standalone images with paragraph tag
