---
baseURL: "http://travisbeckham.com/"
title: "Travis Beckham"
paginate: 10
disableKinds: ["RSS"]
taxonomies:
  tag: tags
params:
  projectImgDir: "/img/projects/"
  thumbnailBaseName: "tn"
  datetimeFormat: "Jan 2, 2006 @ 3:04pm"
...
