---
baseURL: "http://everythingisabox.com/"
title: "Everything is a box"
disableKinds: ["RSS"]
taxonomies:
  tag: tags
params:
  projectImgDir: "/img/projects/"
  thumbnailBaseName: "tn"
  datetimeFormat: "Jan 2, 2006 @ 3:04pm"
...
